CREATE DATABASE SjekkMinHybelDB;
/*Defining*/

CREATE TYPE by_enum AS ENUM (
  'Åkrehamn',
  'Ålesund',
  'Alta',
  'Åndalsnes',
  'Arendal',
  'Ås',
  'Åsgårdstrand',
  'Askim',
  'Askøy',
  'Bergen',
  'Bodø',
  'Brevik',
  'Brønnøysund',
  'Brumunddal',
  'Bryne',
  'Drammen',
  'Drøbak',
  'Egersund',
  'Eidsvoll',
  'Elverum',
  'Fagernes',
  'Fauske',
  'Finnsnes',
  'Flekkefjord',
  'Florø',
  'Førde',
  'Fosnavåg',
  'Fredrikstad',
  'Gjøvik',
  'Grimstad',
  'Halden',
  'Hamar',
  'Hammerfest',
  'Harstad',
  'Haugesund',
  'Hokksund',
  'Holmestrand',
  'Hønefoss',
  'Honningsvåg',
  'Horten',
  'Jessheim',
  'Jørpeland',
  'Kirkenes',
  'Kongsberg',
  'Kongsvinger',
  'Kopervik',
  'Kragerø',
  'Kristiansand',
  'Kristiansund',
  'Langesund',
  'Larvik',
  'Leknes',
  'Levanger',
  'Lillehammer',
  'Lillesand',
  'Lillestrøm',
  'Lyngdal',
  'Mandal',
  'Moelv',
  'Mo i Rana',
  'Molde',
  'Mosjøen',
  'Moss',
  'Nærøy',
  'Namsos',
  'Narvik',
  'Nesoddtangen',
  'Notodden',
  'Odda',
  'Orkanger',
  'Oslo',
  'Otta',
  'Porsgrunn',
  'Raufoss',
  'Risør',
  'Rjukan',
  'Sandefjord',
  'Sandnes',
  'Sandnessjøen',
  'Sandvika',
  'Sauda',
  'Ski',
  'Skien',
  'Sortland',
  'Stavanger',
  'Stavern',
  'Steinkjer',
  'Stjørdal',
  'Stokmarknes',
  'Stord',
  'Svelvik',
  'Svolvær',
  'Tønsberg',
  'Tromsø',
  'Trondheim',
  'Tvedestrand',
  'Ulsteinvik',
  'Vadsø',
  'Vardø',
  'Farsund',
  'Måløy',
  'Verdal',
  'Vestby',
  'Vinstra'
);


CREATE TYPE passer_til_enum as ENUM (
  'Single', 'Par', 'Familie'
);

CREATE TYPE skole_enum AS ENUM (
  'Norges idrettshøgskole',
  'Norges miljø- og biovitenskapelige universitet',
  'Norges musikkhøgskole',
  'Norges teknisk-naturvitenskapelige universitet',
  'Noroff University College',
  'OsloMet - storbyuniversitetet',
  'Politihøgskolen',
  'Sámi allaskuvla/Sámi University of Applied Sciences',
  'UiT Norges arktiske universitet',
  'Universitetet i Agder',
  'Universitetet i Bergen',
  'Universitetet i Oslo',
  'Universitetet i Stavanger',
  'Universitetet i Sørøst-Norge',
  'VID vitenskapelige høgskole',
  'Ansgar høyskole',
  'Arkitektur- og designhøgskolen i Oslo',
  'Barratt Due musikkinstitutt',
  'Dronning Mauds Minne Høgskole for barnehagelærerutdanning',
  'Fjellhaug Internasjonale Høgskole',
  'Forsvarets høgskole',
  'Høgskolen i Innlandet',
  'Høgskolen i Molde - Vitenskapelig høgskole i logistikk',
  'Høgskolen i Østfold',
  'Høgskulen i Volda',
  'Høgskulen på Vestlandet',
  'Høyskolen Kristiania',
  'Kriminalomsorgens høgskole og utdanningssenter KRUS',
  'Kunsthøgskolen i Oslo',
  'Løvensberg diakonale høgskole',
  'MF vitenskapelig høyskole for teologi, religion og samfunn',
  'NLA Høgskolen',
  'Nord universitet',
  'Norges Handelshøyskole',
  'Handelshøyskolen BI' 
);




CREATE TABLE By(
  by_id SERIAL PRIMARY KEY,
  by by_enum
);

CREATE TABLE Skole(
  skole_id SERIAL PRMARY KEY,
  school_name skole_enum
)

CREATE TABLE Users (
  user_id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,  -- Assuming email addresses are unique and required.
  password VARCHAR(255) NOT NULL,       -- Assuming you will store hashed passwords.
  post_quantity INT CHECK(post_quantity <= 2)
);

CREATE TABLE posts(
  post_id SERIAL PRIMARY KEY,
  user_id INT REFERENCES Users(user_id),
  school_name VARCHAR (100) NOT NULL,
  city VARCHAR (50) NOT NULL,
  sted VARCHAR (50) NOT NULL,
  passer VARCHAR (20) NOT NULL,
  rate_plassering INT CHECK (rate_plassering >= 0 AND rate_plassering <= 5),
  rate_byggning INT CHECK (rate_byggning >= 0 AND rate_byggning <= 5),
  rate_badet INT CHECK (rate_badet >= 0 AND rate_badet <= 5),
  rate_kjokkenet INT CHECK (rate_kjokkenet >= 0 AND rate_kjokkenet <= 5),
  description_good VARCHAR(300),
  description_bad VARCHAR(300),
  bilder BYTEA[5],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  approved BOOLEAN DEFAULT FALSE
);